project: coconut
save_path: ./ckpts_100326
name: traj_qwen3_0p6b_stage2_simcot_new

only_eval: False

# Core switches
coconut: True
cot: False
no_thoughts: False
no_cot: False

# Latent schedule (обычно оставляют тем же)
c_thought: 2
epochs_per_stage: 3
max_latent_stage: 5
pad_latent_to_max: True
uniform_prob: 0.0

# Model: стартуем со Stage-1 чекпоинта
model_id: Qwen/Qwen3-0.6B
load_model_path: ./ckpts_100326/traj_qwen3_0p6b_stage1_coconut/checkpoint_25
save_only_improve: False

# Train
wandb: False
seed: 0
resume: 25
auto_resume: false
bf16: True
attn_implementation: eager
force_math_sdp: true

train_path: resolved_trajectories_openai__Qwen__Qwen3-Coder-30B-A3B-Instruct.eval_default
val_path: resolved_trajectories_openai__Qwen__Qwen3-Coder-30B-A3B-Instruct.eval_default
steps_field: steps


max_seq_length: 4096
gradient_accumulation_steps: 4
reset_optimizer: True
batch_size_training: 2
debug: False
num_epochs: 10
lr: !!float "1e-5"
weight_decay: 0.01
loss_level: token_level
max_grad_norm: 10.0
loss_log_interval: 1
grad_health_interval: 1
detect_anomaly: true

# IMPORTANT: SIM-CoT mode (как в gsm_simcot.yaml)
mode: coconutgpt_same_word_embedding
explain_mode: v1_aug
training_method: full
