project: coconut
save_path: ./ckpts
name: traj_qwen3_0p6b_stage1_coconut

only_eval: False

# Core switches
coconut: True
cot: False
no_thoughts: False
no_cot: False

# Latent schedule
c_thought: 2
epochs_per_stage: 3
max_latent_stage: 5
pad_latent_to_max: True
uniform_prob: 0.0

# Model
model_id: Qwen/Qwen3-0.6B
load_model_path: "None"
save_only_improve: False

# Train
wandb: False
seed: 0
resume: 0
bf16: True

train_path: resolved_trajectories_openai__Qwen__Qwen3-Coder-30B-A3B-Instruct.eval_default
val_path: resolved_trajectories_openai__Qwen__Qwen3-Coder-30B-A3B-Instruct.eval_default

reset_optimizer: True
batch_size_training: 2
debug: False
max_seq_length: 4096
gradient_accumulation_steps: 4
num_epochs: 25
lr: !!float "1e-4"
weight_decay: 0.01

# IMPORTANT: baseline coconut
mode: coconut_baseline
training_method: full
